<?php

namespace AppBundle\Repository;

/**
 * ChangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ChangesRepository
{
	public function widthChange($animal, $item )
	{

		$width = $animal->getWidth();
		$change = $item->getWidth();
    	$width=$width+ $change;
    	$width = $animal->setWidth($width);

	}

		public function heightChange($animal, $item )
	{

		$height = $animal->getHeight();
		$change = $item->getHeight();
    	$height=$height+$change;
    	$height = $animal->setHeight($height);

	}

	public function energyChange($animal, $item )
	{

		$energy = $animal->getEnergy();
		$change = $item->getEnergy();
    	$energy=$energy+$change;
    	$energy = $animal->setEnergy($energy);

	}

	public function hapinessChange($animal, $item )
	{

		$hapiness = $animal->getHapiness();
		$change = $item->getHapiness();
    	$hapiness=$hapiness+$change;
    	$hapiness = $animal->setHapiness($hapiness);

	}

		public function strengthChange($animal, $item )
	{

		$strength = $animal->getStrength();
		$change = $item->getStrength();
    	$strength=$strength+$change;
    	$strength = $animal->setStrength($strength);

	}



	public function intelligenceChange($animal, $item )
	{

		$intelligence = $animal->getIntelligence();
		$change = $item->getIntelligence();
    	$intelligence=$intelligence+$change;
    	$intelligence = $animal->setIntelligence($intelligence);

	}

		public function sleepinessChange($animal, $item )
	{

		$sleepiness = $animal->getSleepiness();
		$change = $item->getSleepiness();
    	$sleepiness=$sleepiness+$change;
    	$sleepiness = $animal->setSleepiness($sleepiness);

	}

		public function timeChanges($animal)

	{

		$hapiness = $animal->getHapiness();
		if($hapiness>-20)
			{
			$change = rand(0, 1);
			$hapiness=$hapiness -$change;
			$animal->setHapiness($hapiness);
			}
	}

}