<?php

/**
 * Changes repository
 */

namespace AppBundle\Repository;

/**
 * Class ChangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class ChangesRepository
{
   
  /**
  * Changing animal width.
  *
  * @param Animal $animal Animal entity
  * @param object $item
  */
  
 public function widthChange($animal, $item )
    {

        $width = $animal->getWidth();
        $change = $item->getWidth();
        $width=$width+ $change;
        $width = $animal->setWidth($width);

    }

    /**
  * Changing animal height.
  *
  * @param Animal $animal Animal entity
  * @param object $item
  */

    public function heightChange($animal, $item )
    {

        $height = $animal->getHeight();
        $change = $item->getHeight();
         $height=$height+$change;
         $height = $animal->setHeight($height);

    }


    /**
  * Changing animal energy.
  *
  * @param Animal $animal Animal entity
  * @param object $item
  */

    public function energyChange($animal, $item )
    {

        $energy = $animal->getEnergy();
        $change = $item->getEnergy();
        $energy=$energy+$change;
        $energy = $animal->setEnergy($energy);

    }


    /**
  * Changing animal hapiness.
  *
  * @param Animal $animal Animal entity
  * @param object $item
  */
    public function hapinessChange($animal, $item )
    {

        $hapiness = $animal->getHapiness();
        $change = $item->getHapiness();
        $hapiness=$hapiness+$change;
        $hapiness = $animal->setHapiness($hapiness);

    }

    /**
  * Changing animal strength.
  *
  * @param Animal $animal Animal entity
  * @param object $item
  */

    public function strengthChange($animal, $item )
    {

        $strength = $animal->getStrength();
        $change = $item->getStrength();
         $strength=$strength+$change;
         $strength = $animal->setStrength($strength);

    }



    /**
  * Changing animal intelligence.
  *
  * @param Animal $animal Animal entity
  * @param object $item
  */
    public function intelligenceChange($animal, $item )
    {

        $intelligence = $animal->getIntelligence();
        $change = $item->getIntelligence();
        $intelligence=$intelligence+$change;
        $intelligence = $animal->setIntelligence($intelligence);

    }


    /**
  * Changing animal sleepiness.
  *
  * @param Animal $animal Animal entity
  * @param object $item
  */

    public function sleepinessChange($animal, $item )
    {

        $sleepiness = $animal->getSleepiness();
        $change = $item->getSleepiness();
         $sleepiness=$sleepiness+$change;
         $sleepiness = $animal->setSleepiness($sleepiness);

    }


    /**
  * Changing animal parameters by time.
  *
  * @param Animal $animal Animal entity
  */

    public function timeChanges($animal)    
    {

        $hapiness = $animal->getHapiness();
        if($hapiness>-20) {
             $change = rand(0, 1);
             $hapiness=$hapiness -$change;
             $animal->setHapiness($hapiness);
        }
    }

}