<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Logs;

/**
 * LogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogsRepository extends EntityRepository
{

	public function make_log($event)
	{	$date = date_create('now');
		$log = new Logs();
     	$log->setDate($date);
     	$log->setEvent($event);
		$em = $this ->getEntityManager();
		$em->persist($log);
    	$em->flush();

	}


}
