<?php

/**
 * Player repository
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Class PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
}
