<?php

/**
 * Toy repository
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Toy;

/**
 * ToyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ToyRepository extends EntityRepository
{

        /**
     * Save entity.
     *
     * @param Toy $toy Toy entity
     */
    public function save(Toy $toy)
    {
        $this->_em->persist($toy);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Toy $toy Toy entity
     */
    public function delete(Toy $toy)
    {
        $this->_em->remove($toy);
        $this->_em->flush();
    }
}
